// Code generated by codegen/generate.py; DO NOT EDIT.


//! Generated constructor smoke test. Calls every per-provider
//! factory and the generic new_client escape hatch.

use llmkit::builders::{
    new_client, Client,
    ai21, anthropic, assemblyai, azure,
    bedrock, cerebras, cohere, deepseek,
    doubao, ernie, fireworks, google,
    grok, groq, inworld, jan,
    llamacpp, lmstudio, minimax, mistral,
    moonshot, ollama, openai, openrouter,
    perplexity, pixverse, qwen, recraft,
    sambanova, together, vertex, vidu,
    vllm, workersai, yi, zhipu,
};
use llmkit::ProviderName;

#[test]
fn every_per_provider_factory_constructs_client() {
    let pairs: Vec<(&str, fn(&str) -> Client)> = vec![
        ("ai21", |k| ai21(k)),
        ("anthropic", |k| anthropic(k)),
        ("assemblyai", |k| assemblyai(k)),
        ("azure", |k| azure(k)),
        ("bedrock", |k| bedrock(k)),
        ("cerebras", |k| cerebras(k)),
        ("cohere", |k| cohere(k)),
        ("deepseek", |k| deepseek(k)),
        ("doubao", |k| doubao(k)),
        ("ernie", |k| ernie(k)),
        ("fireworks", |k| fireworks(k)),
        ("google", |k| google(k)),
        ("grok", |k| grok(k)),
        ("groq", |k| groq(k)),
        ("inworld", |k| inworld(k)),
        ("jan", |k| jan(k)),
        ("llamacpp", |k| llamacpp(k)),
        ("lmstudio", |k| lmstudio(k)),
        ("minimax", |k| minimax(k)),
        ("mistral", |k| mistral(k)),
        ("moonshot", |k| moonshot(k)),
        ("ollama", |k| ollama(k)),
        ("openai", |k| openai(k)),
        ("openrouter", |k| openrouter(k)),
        ("perplexity", |k| perplexity(k)),
        ("pixverse", |k| pixverse(k)),
        ("qwen", |k| qwen(k)),
        ("recraft", |k| recraft(k)),
        ("sambanova", |k| sambanova(k)),
        ("together", |k| together(k)),
        ("vertex", |k| vertex(k)),
        ("vidu", |k| vidu(k)),
        ("vllm", |k| vllm(k)),
        ("workersai", |k| workersai(k)),
        ("yi", |k| yi(k)),
        ("zhipu", |k| zhipu(k)),
    ];
    assert_eq!(pairs.len(), 36);
    for (_label, factory) in pairs {
        let c = factory("k");
        assert_eq!(c.provider.api_key, "k");
    }
    // Generic escape hatch — exercises the new_client path.
    let c = new_client(ProviderName::OpenAI, "k");
    assert_eq!(c.provider.api_key, "k");
}
