// Code generated by codegen/generate.py; DO NOT EDIT.

//! Catalogue builder types (ADR-019). Chain methods take `mut self`
//! and return `Self` for chain immutability via ownership transfer.
//! HTTP-touching terminals delegate to hand-coded runtime in
//! `crate::models`.

use super::{Client};
use crate::models::{
    catalogue_filter, catalogue_lookup, catalogue_providers_list,
    catalogue_providers_supported, catalogue_run_get, catalogue_run_list,
    catalogue_run_live, CatalogueError,
};
use crate::structs::{LiveResult, ModelInfo};
use crate::types::{Capability, Provider};

/// Models is the catalogue builder. Chain methods consume `self` and
/// return a fresh `Models`; `list`/`get` walk the compiled-in slice
/// synchronously, `live().await` fans out HTTP across configured
/// providers, `provider(p)` returns `ScopedModels`.
#[derive(Clone, Debug)]
pub struct Models {
    pub client: Client,
    pub cap_filter: Option<Capability>,
}

impl Models {
    pub(crate) fn new(client: Client) -> Self {
        Self { client, cap_filter: None }
    }

    /// Filter the catalogue to models whose ontology-derived capabilities
    /// slice contains `c`. Composes with `list` / `live` / `provider(p).list`.
    pub fn with_capability(mut self, c: Capability) -> Self {
        self.cap_filter = Some(c);
        self
    }

    /// Scope the catalogue to a single provider; returns `ScopedModels`
    /// on which `raw()`, `list().await`, and `get(id).await` are reachable.
    pub fn provider(&self, p: Provider) -> ScopedModels {
        ScopedModels {
            client: self.client.clone(),
            target: p,
            cap_filter: self.cap_filter,
            raw_flag: false,
        }
    }

    /// Returns the compiled-in catalogue, filtered by `with_capability`
    /// when set. Sync, no IO.
    pub fn list(&self) -> Vec<ModelInfo> {
        catalogue_filter(self.cap_filter)
    }

    /// Returns a compiled-in model by id, or `None` when no entry matches.
    pub fn get(&self, id: &str) -> Option<ModelInfo> {
        catalogue_lookup(id)
    }

    /// Walk every provider this `Client` is credentialed for and return
    /// an aggregated `LiveResult`. Today a `Client` carries one provider,
    /// so the result is 0 or 1 underlying calls; the API shape leaves
    /// room for a future multi-credential `Client` without breaking
    /// callers. `with_capability` composes post-fetch.
    pub async fn live(&self) -> LiveResult {
        catalogue_run_live(self).await
    }
}

/// ScopedModels is the single-provider live-catalogue sub-builder.
/// Reached via `Models::provider(p)`. `raw()` opts into populating
/// `ModelInfo.raw` per ADR-014.
#[derive(Clone, Debug)]
pub struct ScopedModels {
    pub client: Client,
    pub target: Provider,
    pub cap_filter: Option<Capability>,
    pub raw_flag: bool,
}

impl ScopedModels {
    pub fn raw(mut self) -> Self {
        self.raw_flag = true;
        self
    }

    pub async fn list(&self) -> Result<Vec<ModelInfo>, CatalogueError> {
        catalogue_run_list(self).await
    }

    pub async fn get(&self, id: &str) -> Result<ModelInfo, CatalogueError> {
        catalogue_run_get(self, id).await
    }
}

/// Providers is the providers-namespace prototype. `list()` returns
/// providers with both credentials configured and `llm:hasModelsEndpoint`
/// declared; `supported()` returns the SDK roster.
#[derive(Clone, Debug)]
pub struct Providers {
    pub client: Client,
}

impl Providers {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    pub fn list(&self) -> Vec<Provider> {
        catalogue_providers_list(&self.client)
    }

    pub fn supported(&self) -> Vec<Provider> {
        catalogue_providers_supported()
    }
}
