//! Typed-builder API surface introduced in ADR-009 / plan 016.
//!
//! As of phase 3 every terminal is wired against the legacy
//! free-function runtime in a hand-written sibling module
//! (text.rs, image.rs, batch.rs, stream.rs, upload.rs, agent.rs).
//! Phase 4 will move this surface into the main module once the
//! legacy free-function surface is deleted.

// Code generated by codegen/generate.py; DO NOT EDIT.

mod agent;
mod batch;
mod image;
mod music;
mod stream;
mod text;
mod upload;
mod video;
#[cfg(test)]
mod internal_tests;

use self::agent::{agent_prompt, agent_reset};
use self::batch::{text_batch, text_submit_batch};
use self::image::{image_generate};
use self::music::{music_generate};
use self::stream::{text_stream};
use self::text::{text_prompt};
use self::upload::{upload_run};
use self::video::{video_submit};
pub use self::agent::{AgentState};
pub use self::batch::{BatchHandleExt};
pub use self::video::{VideoHandleExt};

use crate::error::Error;
use crate::image::Part;
use crate::middleware::MiddlewareFn;
use crate::providers::generated::batch::batch_config;
use crate::providers::generated::caching::caching_config;
use crate::providers::generated::image_gen::image_gen_config;
use crate::providers::generated::request::file_upload_config;
use crate::structs::{BatchHandle, File, ImageResponse, Message, MusicResponse, Response, VideoHandle};
use crate::types::{Capability, Tool};
use crate::ProviderName;

// Re-exports so callers can `use llmkit::builders::{ImageData, MediaRef, ...}`
// without reaching into sibling modules.
pub use crate::image::{ImageData, MediaRef};

/// Provider configuration carried by a [`Client`]. Use [`Client::new`]
/// or one of the per-provider helpers (`anthropic(...)`, `openai(...)`,
/// ...) to construct one; mutate `base_url` via [`Client::with_base_url`]
/// if you need to point at a self-hosted endpoint or a local mock.
#[derive(Clone, Debug)]
#[non_exhaustive]
pub struct ProviderConfig {
    pub name: ProviderName,
    /// API key. Wrap or zeroize at the call site if you need defence
    /// against accidental logging — the library prints it via the
    /// derived `Debug`.
    pub api_key: String,
    pub base_url: Option<String>,
}

/// Entry point for the typed-builder API. Hold one per (provider, key)
/// pair. `Clone` copies the inner `ProviderConfig` (one `String`
/// allocation for the API key); cheap relative to per-request HTTP,
/// expensive relative to an `Arc`. Phase 3 may wrap in `Arc` once
/// fan-out lands.
///
/// `Debug` is derived for `tracing::instrument` ergonomics; the
/// `api_key` field is printed verbatim. Wrap/zeroize at the call site
/// if your logs may leak.
#[derive(Clone, Debug)]
pub struct Client {
    pub provider: ProviderConfig,
}

impl Client {
    pub fn new(name: ProviderName, api_key: impl Into<String>) -> Self {
        Self {
            provider: ProviderConfig {
                name,
                api_key: api_key.into(),
                base_url: None,
            },
        }
    }

    /// Override the default API base URL. Typical production use:
    /// pointing OpenAI-compatible providers (vLLM, LM Studio, Ollama,
    /// corporate gateways) at a self-hosted endpoint. Also used by
    /// integration tests to redirect requests at a mock server.
    pub fn with_base_url(mut self, url: impl Into<String>) -> Self {
        self.provider.base_url = Some(url.into());
        self
    }

    /// True iff an explicit request for `cap` will not hard-fail
    /// pre-flight on this client's provider (ADR-030). Gated arms
    /// dispatch the same generated lookups as the strict validation
    /// paths; capabilities with no provider-level gate return `true`.
    /// Says nothing about per-model or per-option rejections — use the
    /// catalogue's `ModelInfo.capabilities` for model-level facts.
    /// Sync, no IO, infallible.
    pub fn supports(&self, cap: Capability) -> bool {
        match cap {
            Capability::Caching => caching_config(self.provider.name).is_some(),
            Capability::Batching => batch_config(self.provider.name).is_some(),
            Capability::FileUpload => file_upload_config(self.provider.name).is_some(),
            Capability::ImageGeneration => image_gen_config(self.provider.name).is_some(),
            _ => true,
        }
    }

    /// ChatCompletion builder.
    pub fn text(&self) -> Text {
        Text::new(self.clone())
    }
    /// ImageGeneration builder.
    pub fn image(&self) -> Image {
        Image::new(self.clone())
    }
    /// MusicGeneration builder.
    pub fn music(&self) -> Music {
        Music::new(self.clone())
    }
    /// VideoGeneration builder.
    pub fn video(&self) -> Video {
        Video::new(self.clone())
    }
    /// ToolCalling builder.
    pub fn agent(&self) -> Agent {
        Agent::new(self.clone())
    }
    /// FileUpload builder.
    pub fn upload(&self) -> Upload {
        Upload::new(self.clone())
    }
    /// Catalogue namespace: compiled-in + live model lookup.
    pub fn models(&self) -> catalogue::Models {
        catalogue::Models::new(self.clone())
    }
    /// Providers namespace: configured + supported provider lookup.
    pub fn providers(&self) -> catalogue::Providers {
        catalogue::Providers::new(self.clone())
    }
}

/// ADR-019 catalogue builders live in a sibling module.
pub mod catalogue;
pub use catalogue::{Models, Providers, ScopedModels};

/// Generic factory; per-provider helpers below are ergonomic shortcuts.
pub fn new_client(name: ProviderName, api_key: impl Into<String>) -> Client {
    Client::new(name, api_key)
}

// === Per-provider factory functions ===
pub fn ai21(api_key: impl Into<String>) -> Client { Client::new(ProviderName::AI21, api_key) }
pub fn anthropic(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Anthropic, api_key) }
pub fn azure(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Azure, api_key) }
pub fn bedrock(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Bedrock, api_key) }
pub fn cerebras(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Cerebras, api_key) }
pub fn cohere(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Cohere, api_key) }
pub fn deepseek(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Deepseek, api_key) }
pub fn doubao(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Doubao, api_key) }
pub fn ernie(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Ernie, api_key) }
pub fn fireworks(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Fireworks, api_key) }
pub fn google(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Google, api_key) }
pub fn grok(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Grok, api_key) }
pub fn groq(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Groq, api_key) }
pub fn jan(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Jan, api_key) }
pub fn llamacpp(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Llamacpp, api_key) }
pub fn lmstudio(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Lmstudio, api_key) }
pub fn minimax(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Minimax, api_key) }
pub fn mistral(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Mistral, api_key) }
pub fn moonshot(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Moonshot, api_key) }
pub fn ollama(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Ollama, api_key) }
pub fn openai(api_key: impl Into<String>) -> Client { Client::new(ProviderName::OpenAI, api_key) }
pub fn openrouter(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Openrouter, api_key) }
pub fn perplexity(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Perplexity, api_key) }
pub fn qwen(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Qwen, api_key) }
pub fn sambanova(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Sambanova, api_key) }
pub fn together(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Together, api_key) }
pub fn vertex(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Vertex, api_key) }
pub fn vllm(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Vllm, api_key) }
pub fn yi(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Yi, api_key) }
pub fn zhipu(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Zhipu, api_key) }

// === Text — ChatCompletion builder ===

#[derive(Clone)]
#[non_exhaustive]
pub struct Text {
    pub(crate) client: Client,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) caching: bool,
    pub(crate) files: Vec<File>,
    pub(crate) frequency_penalty: Option<f64>,
    pub(crate) history: Vec<Message>,
    pub(crate) parts: Vec<Part>,
    pub(crate) max_tokens: Option<u32>,
    pub(crate) model: Option<String>,
    pub(crate) presence_penalty: Option<f64>,
    pub(crate) raw: bool,
    pub(crate) reasoning_effort: Option<String>,
    pub(crate) safety_settings: Vec<crate::types::SafetySetting>,
    pub(crate) schema: Option<String>,
    pub(crate) seed: Option<i64>,
    pub(crate) stop_sequences: Vec<String>,
    pub(crate) system: Option<String>,
    pub(crate) temperature: Option<f64>,
    pub(crate) thinking_budget: Option<u32>,
    pub(crate) top_k: Option<u32>,
    pub(crate) top_p: Option<f64>,
}

impl Text {
    fn new(client: Client) -> Self {
        Self {
            client,
            middleware: Vec::new(),
            caching: false,
            files: Vec::new(),
            frequency_penalty: None,
            history: Vec::new(),
            parts: Vec::new(),
            max_tokens: None,
            model: None,
            presence_penalty: None,
            raw: false,
            reasoning_effort: None,
            safety_settings: Vec::new(),
            schema: None,
            seed: None,
            stop_sequences: Vec::new(),
            system: None,
            temperature: None,
            thinking_budget: None,
            top_k: None,
            top_p: None,
        }
    }

    pub fn add_middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self
    }

    pub fn caching(mut self) -> Self {
        self.caching = true;
        self
    }

    pub fn file(mut self, id: impl Into<String>) -> Self {  // ordered
        self.files.push(File { id: id.into(), uri: String::new(), mime_type: String::new(), name: String::new() });
        self
    }

    pub fn frequency_penalty(mut self, v: f64) -> Self {
        self.frequency_penalty = Some(v);
        self
    }

    pub fn history(mut self, msgs: Vec<Message>) -> Self {
        self.history = msgs;
        self
    }

    pub fn image(mut self, mime: impl Into<String>, data: Vec<u8>) -> Self {  // ordered
        self.parts.push(Part::image(mime, data));
        self
    }

    pub fn max_tokens(mut self, n: u32) -> Self {
        self.max_tokens = Some(n);
        self
    }

    pub fn model(mut self, name: impl Into<String>) -> Self {
        self.model = Some(name.into());
        self
    }

    pub fn presence_penalty(mut self, v: f64) -> Self {
        self.presence_penalty = Some(v);
        self
    }

    pub fn raw(mut self) -> Self {
        self.raw = true;
        self
    }

    pub fn reasoning_effort(mut self, level: impl Into<String>) -> Self {
        self.reasoning_effort = Some(level.into());
        self
    }

    pub fn safety_settings(mut self, s: Vec<crate::types::SafetySetting>) -> Self {
        self.safety_settings = s;
        self
    }

    pub fn schema(mut self, s: impl Into<String>) -> Self {
        self.schema = Some(s.into());
        self
    }

    pub fn seed(mut self, n: i64) -> Self {
        self.seed = Some(n);
        self
    }

    pub fn stop_sequences(mut self, seqs: Vec<String>) -> Self {
        self.stop_sequences = seqs.into_iter().map(Into::into).collect();
        self
    }

    pub fn system(mut self, s: impl Into<String>) -> Self {
        self.system = Some(s.into());
        self
    }

    pub fn temperature(mut self, t: f64) -> Self {
        self.temperature = Some(t);
        self
    }

    pub fn text(mut self, s: impl Into<String>) -> Self {  // ordered
        self.parts.push(Part::text(s));
        self
    }

    pub fn thinking_budget(mut self, n: u32) -> Self {
        self.thinking_budget = Some(n);
        self
    }

    pub fn top_k(mut self, n: u32) -> Self {
        self.top_k = Some(n);
        self
    }

    pub fn top_p(mut self, v: f64) -> Self {
        self.top_p = Some(v);
        self
    }

    pub async fn prompt(self, msg: impl Into<String>) -> Result<Response, Error> {
        text_prompt(self, msg).await
    }

    pub async fn stream(self, msg: impl Into<String>, callback: impl FnMut(&str)) -> Result<Response, Error> {
        text_stream(self, msg, callback).await
    }

    pub async fn batch(self, prompts: Vec<String>) -> Result<Vec<Response>, Error> {
        text_batch(self, prompts).await
    }

    pub async fn submit_batch(self, prompts: Vec<String>) -> Result<BatchHandle, Error> {
        text_submit_batch(self, prompts).await
    }

}

// === Image — ImageGeneration builder ===

#[derive(Clone)]
#[non_exhaustive]
pub struct Image {
    pub(crate) client: Client,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) aspect_ratio: Option<String>,
    pub(crate) background: Option<String>,
    pub(crate) count: Option<u32>,
    pub(crate) parts: Vec<Part>,
    pub(crate) image_size: Option<String>,
    pub(crate) include_text: bool,
    pub(crate) mask: Option<crate::image::MediaRef>,
    pub(crate) model: Option<String>,
    pub(crate) output_format: Option<String>,
    pub(crate) quality: Option<String>,
    pub(crate) raw: bool,
    pub(crate) safety_filter: Option<String>,
    pub(crate) safety_settings: Vec<crate::types::SafetySetting>,
    pub(crate) extra_fields: std::collections::HashMap<String, serde_json::Value>,
}

impl Image {
    fn new(client: Client) -> Self {
        Self {
            client,
            middleware: Vec::new(),
            aspect_ratio: None,
            background: None,
            count: None,
            parts: Vec::new(),
            image_size: None,
            include_text: false,
            mask: None,
            model: None,
            output_format: None,
            quality: None,
            raw: false,
            safety_filter: None,
            safety_settings: Vec::new(),
            extra_fields: std::collections::HashMap::new(),
        }
    }

    pub fn add_middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self
    }

    pub fn aspect_ratio(mut self, r: impl Into<String>) -> Self {
        self.aspect_ratio = Some(r.into());
        self
    }

    pub fn background(mut self, s: impl Into<String>) -> Self {
        self.background = Some(s.into());
        self
    }

    pub fn count(mut self, n: u32) -> Self {
        self.count = Some(n);
        self
    }

    pub fn image(mut self, mime: impl Into<String>, data: Vec<u8>) -> Self {  // ordered
        self.parts.push(Part::image(mime, data));
        self
    }

    pub fn image_size(mut self, s: impl Into<String>) -> Self {
        self.image_size = Some(s.into());
        self
    }

    pub fn include_text(mut self) -> Self {
        self.include_text = true;
        self
    }

    pub fn mask(mut self, mime: impl Into<String>, data: Vec<u8>) -> Self {
        self.mask = Some(crate::image::MediaRef { mime_type: mime.into(), bytes: data });
        self
    }

    pub fn model(mut self, name: impl Into<String>) -> Self {
        self.model = Some(name.into());
        self
    }

    pub fn output_format(mut self, s: impl Into<String>) -> Self {
        self.output_format = Some(s.into());
        self
    }

    pub fn quality(mut self, s: impl Into<String>) -> Self {
        self.quality = Some(s.into());
        self
    }

    pub fn raw(mut self) -> Self {
        self.raw = true;
        self
    }

    pub fn safety_filter(mut self, s: impl Into<String>) -> Self {
        self.safety_filter = Some(s.into());
        self
    }

    pub fn safety_settings(mut self, s: Vec<crate::types::SafetySetting>) -> Self {
        self.safety_settings = s;
        self
    }

    pub fn text(mut self, s: impl Into<String>) -> Self {  // ordered
        self.parts.push(Part::text(s));
        self
    }

    pub fn extra_fields(
        mut self,
        extras: std::collections::HashMap<String, serde_json::Value>,
    ) -> Self {
        for (k, v) in extras {
            self.extra_fields.insert(k, v);
        }
        self
    }

    pub async fn generate(self, msg: impl Into<String>) -> Result<ImageResponse, Error> {
        image_generate(self, msg).await
    }

}

// === Music — MusicGeneration builder ===

#[derive(Clone)]
#[non_exhaustive]
pub struct Music {
    pub(crate) client: Client,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) parts: Vec<Part>,
    pub(crate) model: Option<String>,
    pub(crate) raw: bool,
}

impl Music {
    fn new(client: Client) -> Self {
        Self {
            client,
            middleware: Vec::new(),
            parts: Vec::new(),
            model: None,
            raw: false,
        }
    }

    pub fn add_middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self
    }

    pub fn lyrics(mut self, s: impl Into<String>) -> Self {  // ordered
        self.parts.push(Part::lyrics(s));
        self
    }

    pub fn model(mut self, name: impl Into<String>) -> Self {
        self.model = Some(name.into());
        self
    }

    pub fn raw(mut self) -> Self {
        self.raw = true;
        self
    }

    pub fn text(mut self, s: impl Into<String>) -> Self {  // ordered
        self.parts.push(Part::text(s));
        self
    }

    pub async fn generate(self, msg: impl Into<String>) -> Result<MusicResponse, Error> {
        music_generate(self, msg).await
    }

}

// === Video — VideoGeneration builder ===

#[derive(Clone)]
#[non_exhaustive]
pub struct Video {
    pub(crate) client: Client,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) model: Option<String>,
    pub(crate) output_uri: Option<String>,
    pub(crate) raw: bool,
    pub(crate) parts: Vec<Part>,
}

impl Video {
    fn new(client: Client) -> Self {
        Self {
            client,
            middleware: Vec::new(),
            model: None,
            output_uri: None,
            raw: false,
            parts: Vec::new(),
        }
    }

    pub fn add_middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self
    }

    pub fn model(mut self, name: impl Into<String>) -> Self {
        self.model = Some(name.into());
        self
    }

    pub fn output_uri(mut self, uri: impl Into<String>) -> Self {
        self.output_uri = Some(uri.into());
        self
    }

    pub fn raw(mut self) -> Self {
        self.raw = true;
        self
    }

    pub fn text(mut self, s: impl Into<String>) -> Self {  // ordered
        self.parts.push(Part::text(s));
        self
    }

    pub async fn submit(self, msg: impl Into<String>) -> Result<VideoHandle, Error> {
        video_submit(self, msg).await
    }

}

// === Agent — ToolCalling builder ===

#[non_exhaustive]
pub struct Agent {
    pub(crate) client: Client,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) tools: Vec<Tool>,
    pub(crate) caching: bool,
    pub(crate) frequency_penalty: Option<f64>,
    pub(crate) history: Vec<Message>,
    pub(crate) max_tokens: Option<u32>,
    pub(crate) max_tool_iterations: Option<u32>,
    pub(crate) model: Option<String>,
    pub(crate) presence_penalty: Option<f64>,
    pub(crate) raw: bool,
    pub(crate) reasoning_effort: Option<String>,
    pub(crate) safety_settings: Vec<crate::types::SafetySetting>,
    pub(crate) seed: Option<i64>,
    pub(crate) stop_sequences: Vec<String>,
    pub(crate) system: Option<String>,
    pub(crate) temperature: Option<f64>,
    pub(crate) thinking_budget: Option<u32>,
    pub(crate) top_k: Option<u32>,
    pub(crate) top_p: Option<f64>,
    pub(crate) state: Option<AgentState>,
}

impl Agent {
    fn new(client: Client) -> Self {
        Self {
            client,
            middleware: Vec::new(),
            tools: Vec::new(),
            caching: false,
            frequency_penalty: None,
            history: Vec::new(),
            max_tokens: None,
            max_tool_iterations: None,
            model: None,
            presence_penalty: None,
            raw: false,
            reasoning_effort: None,
            safety_settings: Vec::new(),
            seed: None,
            stop_sequences: Vec::new(),
            system: None,
            temperature: None,
            thinking_budget: None,
            top_k: None,
            top_p: None,
            state: None,
        }
    }

    pub fn add_middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self.state = None;
        self
    }

    pub fn add_tool(mut self, t: Tool) -> Self {
        self.tools.push(t);
        self.state = None;
        self
    }

    pub fn caching(mut self) -> Self {
        self.caching = true;
        self.state = None;
        self
    }

    pub fn frequency_penalty(mut self, v: f64) -> Self {
        self.frequency_penalty = Some(v);
        self.state = None;
        self
    }

    pub fn history(mut self, msgs: Vec<Message>) -> Self {
        self.history = msgs;
        self.state = None;
        self
    }

    pub fn max_tokens(mut self, n: u32) -> Self {
        self.max_tokens = Some(n);
        self.state = None;
        self
    }

    pub fn max_tool_iterations(mut self, n: u32) -> Self {
        self.max_tool_iterations = Some(n);
        self.state = None;
        self
    }

    pub fn model(mut self, name: impl Into<String>) -> Self {
        self.model = Some(name.into());
        self.state = None;
        self
    }

    pub fn presence_penalty(mut self, v: f64) -> Self {
        self.presence_penalty = Some(v);
        self.state = None;
        self
    }

    pub fn raw(mut self) -> Self {
        self.raw = true;
        self.state = None;
        self
    }

    pub fn reasoning_effort(mut self, level: impl Into<String>) -> Self {
        self.reasoning_effort = Some(level.into());
        self.state = None;
        self
    }

    pub fn safety_settings(mut self, s: Vec<crate::types::SafetySetting>) -> Self {
        self.safety_settings = s;
        self.state = None;
        self
    }

    pub fn seed(mut self, n: i64) -> Self {
        self.seed = Some(n);
        self.state = None;
        self
    }

    pub fn stop_sequences(mut self, seqs: Vec<String>) -> Self {
        self.stop_sequences = seqs.into_iter().map(Into::into).collect();
        self.state = None;
        self
    }

    pub fn system(mut self, s: impl Into<String>) -> Self {
        self.system = Some(s.into());
        self.state = None;
        self
    }

    pub fn temperature(mut self, t: f64) -> Self {
        self.temperature = Some(t);
        self.state = None;
        self
    }

    pub fn thinking_budget(mut self, n: u32) -> Self {
        self.thinking_budget = Some(n);
        self.state = None;
        self
    }

    pub fn top_k(mut self, n: u32) -> Self {
        self.top_k = Some(n);
        self.state = None;
        self
    }

    pub fn top_p(mut self, v: f64) -> Self {
        self.top_p = Some(v);
        self.state = None;
        self
    }

    /// bot.messages() returns the agent's accumulated history as
    /// public Message values (ADR-020 HIST-004). Empty before the
    /// first .prompt() call.
    pub fn messages(&self) -> Vec<crate::structs::Message> {
        match &self.state {
            Some(state) => state.public_messages(),
            None => Vec::new(),
        }
    }

    /// bot.save() serializes the agent's accumulated history
    /// into the canonical wire format (ADR-023 STAB-012).
    pub fn save(&self) -> Result<String, crate::wire::WireError> {
        crate::wire::save_history(&self.messages())
    }

    /// bot.load(data) decodes a wire document, replaces the
    /// chain's history list, and clears runtime state so the
    /// next prompt rebuilds the legacy agent with the loaded
    /// history (ADR-023 STAB-012).
    pub fn load(mut self, data: &str) -> Result<Self, crate::wire::WireError> {
        let msgs = crate::wire::load_history(data)?;
        self.history = msgs;
        self.state = None;
        Ok(self)
    }

    pub async fn prompt(&mut self, msg: impl Into<String>) -> Result<Response, Error> {
        agent_prompt(self, msg).await
    }

    pub fn reset(&mut self) {
        agent_reset(self)
    }

}

// === Upload — FileUpload builder ===

#[derive(Clone)]
#[non_exhaustive]
pub struct Upload {
    pub(crate) client: Client,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) bytes: Vec<u8>,
    pub(crate) filename: Option<String>,
    pub(crate) mime_type: Option<String>,
    pub(crate) path: Option<String>,
}

impl Upload {
    fn new(client: Client) -> Self {
        Self {
            client,
            middleware: Vec::new(),
            bytes: Vec::new(),
            filename: None,
            mime_type: None,
            path: None,
        }
    }

    pub fn add_middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self
    }

    pub fn bytes(mut self, data: Vec<u8>) -> Self {
        self.bytes = data;
        self
    }

    pub fn filename(mut self, name: impl Into<String>) -> Self {
        self.filename = Some(name.into());
        self
    }

    pub fn mime_type(mut self, mime: impl Into<String>) -> Self {
        self.mime_type = Some(mime.into());
        self
    }

    pub fn path(mut self, p: impl Into<String>) -> Self {
        self.path = Some(p.into());
        self
    }

    pub async fn run(self) -> Result<File, Error> {
        upload_run(self).await
    }

}

