//! Typed-builder API surface introduced in ADR-009 / plan 016.
//!
//! As of phase 3 every terminal is wired against the legacy
//! free-function runtime in a hand-written sibling module
//! (text.rs, image.rs, batch.rs, stream.rs, upload.rs, agent.rs).
//! Phase 4 will move this surface into the main module once the
//! legacy free-function surface is deleted.

// Code generated by codegen/generate.py; DO NOT EDIT.

mod agent;
mod batch;
mod image;
mod stream;
mod text;
mod upload;
#[cfg(test)]
mod internal_tests;

use self::agent::{agent_prompt, agent_reset};
use self::batch::{text_batch, text_submit_batch};
use self::image::{image_generate};
use self::stream::{text_stream};
use self::text::{text_prompt};
use self::upload::{upload_run};
pub use self::agent::{AgentState};
pub use self::batch::{BatchHandleExt};

use crate::batch::BatchHandle;
use crate::error::Error;
use crate::image::{ImageResponse, Part};
use crate::middleware::MiddlewareFn;
use crate::types::{File, Message, Response, Tool};
use crate::ProviderName;

// Re-exports so callers can `use llmkit::builders::{ImageData, MediaRef, ...}`
// without reaching into sibling modules.
pub use crate::image::{ImageData, MediaRef};

/// Provider configuration carried by a [`Client`]. Use [`Client::new`]
/// or one of the per-provider helpers (`anthropic(...)`, `openai(...)`,
/// ...) to construct one; mutate `base_url` via [`Client::with_base_url`]
/// if you need to point at a self-hosted endpoint or a local mock.
#[derive(Clone, Debug)]
#[non_exhaustive]
pub struct ProviderConfig {
    pub name: ProviderName,
    /// API key. Wrap or zeroize at the call site if you need defence
    /// against accidental logging — the library prints it via the
    /// derived `Debug`.
    pub api_key: String,
    pub base_url: Option<String>,
}

/// Entry point for the typed-builder API. Hold one per (provider, key)
/// pair; cheap to clone (just an `Arc`-equivalent of `ProviderConfig`).
#[derive(Clone)]
pub struct Client {
    pub provider: ProviderConfig,
}

impl Client {
    pub fn new(name: ProviderName, api_key: impl Into<String>) -> Self {
        Self {
            provider: ProviderConfig {
                name,
                api_key: api_key.into(),
                base_url: None,
            },
        }
    }

    /// Override the default API base URL. Typical production use:
    /// pointing OpenAI-compatible providers (vLLM, LM Studio, Ollama,
    /// corporate gateways) at a self-hosted endpoint. Also used by
    /// integration tests to redirect requests at a mock server.
    pub fn with_base_url(mut self, url: impl Into<String>) -> Self {
        self.provider.base_url = Some(url.into());
        self
    }

    /// ChatCompletion builder.
    pub fn text(&self) -> Text {
        Text::new(self.clone())
    }
    /// ImageGeneration builder.
    pub fn image(&self) -> Image {
        Image::new(self.clone())
    }
    /// ToolCalling builder.
    pub fn agent(&self) -> Agent {
        Agent::new(self.clone())
    }
    /// FileUpload builder.
    pub fn upload(&self) -> Upload {
        Upload::new(self.clone())
    }
}

/// Generic factory; per-provider helpers below are ergonomic shortcuts.
pub fn new_client(name: ProviderName, api_key: impl Into<String>) -> Client {
    Client::new(name, api_key)
}

// === Per-provider factory functions ===
pub fn ai21(api_key: impl Into<String>) -> Client { Client::new(ProviderName::AI21, api_key) }
pub fn anthropic(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Anthropic, api_key) }
pub fn azure(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Azure, api_key) }
pub fn bedrock(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Bedrock, api_key) }
pub fn cerebras(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Cerebras, api_key) }
pub fn cohere(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Cohere, api_key) }
pub fn deepseek(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Deepseek, api_key) }
pub fn doubao(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Doubao, api_key) }
pub fn ernie(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Ernie, api_key) }
pub fn fireworks(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Fireworks, api_key) }
pub fn google(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Google, api_key) }
pub fn grok(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Grok, api_key) }
pub fn groq(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Groq, api_key) }
pub fn lmstudio(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Lmstudio, api_key) }
pub fn minimax(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Minimax, api_key) }
pub fn mistral(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Mistral, api_key) }
pub fn moonshot(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Moonshot, api_key) }
pub fn ollama(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Ollama, api_key) }
pub fn openai(api_key: impl Into<String>) -> Client { Client::new(ProviderName::OpenAI, api_key) }
pub fn openrouter(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Openrouter, api_key) }
pub fn perplexity(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Perplexity, api_key) }
pub fn qwen(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Qwen, api_key) }
pub fn sambanova(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Sambanova, api_key) }
pub fn together(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Together, api_key) }
pub fn vllm(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Vllm, api_key) }
pub fn yi(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Yi, api_key) }
pub fn zhipu(api_key: impl Into<String>) -> Client { Client::new(ProviderName::Zhipu, api_key) }

// === Text — ChatCompletion builder ===

#[derive(Clone)]
#[non_exhaustive]
pub struct Text {
    pub(crate) client: Client,
    pub(crate) caching: bool,
    pub(crate) files: Vec<File>,
    pub(crate) frequency_penalty: Option<f64>,
    pub(crate) history: Vec<Message>,
    pub(crate) parts: Vec<Part>,
    pub(crate) max_tokens: Option<u32>,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) model: Option<String>,
    pub(crate) presence_penalty: Option<f64>,
    pub(crate) reasoning_effort: Option<String>,
    pub(crate) schema: Option<String>,
    pub(crate) seed: Option<i64>,
    pub(crate) stop_sequences: Vec<String>,
    pub(crate) system: Option<String>,
    pub(crate) temperature: Option<f64>,
    pub(crate) thinking_budget: Option<u32>,
    pub(crate) top_k: Option<u32>,
    pub(crate) top_p: Option<f64>,
}

impl Text {
    fn new(client: Client) -> Self {
        Self {
            client,
            caching: false,
            files: Vec::new(),
            frequency_penalty: None,
            history: Vec::new(),
            parts: Vec::new(),
            max_tokens: None,
            middleware: Vec::new(),
            model: None,
            presence_penalty: None,
            reasoning_effort: None,
            schema: None,
            seed: None,
            stop_sequences: Vec::new(),
            system: None,
            temperature: None,
            thinking_budget: None,
            top_k: None,
            top_p: None,
        }
    }

    pub fn caching(mut self) -> Self {
        self.caching = true;
        self
    }

    pub fn file(mut self, id: impl Into<String>) -> Self {  // ordered
        self.files.push(File { id: id.into(), uri: String::new(), mime_type: String::new(), name: String::new() });
        self
    }

    pub fn frequency_penalty(mut self, v: f64) -> Self {
        self.frequency_penalty = Some(v);
        self
    }

    pub fn history(mut self, msgs: Vec<Message>) -> Self {
        self.history = msgs;
        self
    }

    pub fn image(mut self, mime: impl Into<String>, data: Vec<u8>) -> Self {  // ordered
        self.parts.push(Part::image(mime, data));
        self
    }

    pub fn max_tokens(mut self, n: u32) -> Self {
        self.max_tokens = Some(n);
        self
    }

    pub fn middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self
    }

    pub fn model(mut self, name: impl Into<String>) -> Self {
        self.model = Some(name.into());
        self
    }

    pub fn presence_penalty(mut self, v: f64) -> Self {
        self.presence_penalty = Some(v);
        self
    }

    pub fn reasoning_effort(mut self, level: impl Into<String>) -> Self {
        self.reasoning_effort = Some(level.into());
        self
    }

    pub fn schema(mut self, s: impl Into<String>) -> Self {
        self.schema = Some(s.into());
        self
    }

    pub fn seed(mut self, n: i64) -> Self {
        self.seed = Some(n);
        self
    }

    pub fn stop_sequences(mut self, seqs: Vec<String>) -> Self {
        self.stop_sequences = seqs.into_iter().map(Into::into).collect();
        self
    }

    pub fn system(mut self, s: impl Into<String>) -> Self {
        self.system = Some(s.into());
        self
    }

    pub fn temperature(mut self, t: f64) -> Self {
        self.temperature = Some(t);
        self
    }

    pub fn text(mut self, s: impl Into<String>) -> Self {  // ordered
        self.parts.push(Part::text(s));
        self
    }

    pub fn thinking_budget(mut self, n: u32) -> Self {
        self.thinking_budget = Some(n);
        self
    }

    pub fn top_k(mut self, n: u32) -> Self {
        self.top_k = Some(n);
        self
    }

    pub fn top_p(mut self, v: f64) -> Self {
        self.top_p = Some(v);
        self
    }

    pub async fn prompt(self, msg: impl Into<String>) -> Result<Response, Error> {
        text_prompt(self, msg).await
    }

    pub async fn stream(self, msg: impl Into<String>, callback: impl FnMut(&str)) -> Result<Response, Error> {
        text_stream(self, msg, callback).await
    }

    pub async fn batch(self, prompts: Vec<String>) -> Result<Vec<Response>, Error> {
        text_batch(self, prompts).await
    }

    pub async fn submit_batch(self, prompts: Vec<String>) -> Result<BatchHandle, Error> {
        text_submit_batch(self, prompts).await
    }

}

// === Image — ImageGeneration builder ===

#[derive(Clone)]
#[non_exhaustive]
pub struct Image {
    pub(crate) client: Client,
    pub(crate) aspect_ratio: Option<String>,
    pub(crate) parts: Vec<Part>,
    pub(crate) image_size: Option<String>,
    pub(crate) include_text: bool,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) model: Option<String>,
}

impl Image {
    fn new(client: Client) -> Self {
        Self {
            client,
            aspect_ratio: None,
            parts: Vec::new(),
            image_size: None,
            include_text: false,
            middleware: Vec::new(),
            model: None,
        }
    }

    pub fn aspect_ratio(mut self, r: impl Into<String>) -> Self {
        self.aspect_ratio = Some(r.into());
        self
    }

    pub fn image(mut self, mime: impl Into<String>, data: Vec<u8>) -> Self {  // ordered
        self.parts.push(Part::image(mime, data));
        self
    }

    pub fn image_size(mut self, s: impl Into<String>) -> Self {
        self.image_size = Some(s.into());
        self
    }

    pub fn include_text(mut self) -> Self {
        self.include_text = true;
        self
    }

    pub fn middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self
    }

    pub fn model(mut self, name: impl Into<String>) -> Self {
        self.model = Some(name.into());
        self
    }

    pub fn text(mut self, s: impl Into<String>) -> Self {  // ordered
        self.parts.push(Part::text(s));
        self
    }

    pub async fn generate(self, msg: impl Into<String>) -> Result<ImageResponse, Error> {
        image_generate(self, msg).await
    }

}

// === Agent — ToolCalling builder ===

#[non_exhaustive]
pub struct Agent {
    pub(crate) client: Client,
    pub(crate) caching: bool,
    pub(crate) frequency_penalty: Option<f64>,
    pub(crate) max_tokens: Option<u32>,
    pub(crate) max_tool_iterations: Option<u32>,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) model: Option<String>,
    pub(crate) presence_penalty: Option<f64>,
    pub(crate) reasoning_effort: Option<String>,
    pub(crate) seed: Option<i64>,
    pub(crate) stop_sequences: Vec<String>,
    pub(crate) system: Option<String>,
    pub(crate) temperature: Option<f64>,
    pub(crate) thinking_budget: Option<u32>,
    pub(crate) tools: Vec<Tool>,
    pub(crate) top_k: Option<u32>,
    pub(crate) top_p: Option<f64>,
    pub(crate) state: Option<AgentState>,
}

impl Agent {
    fn new(client: Client) -> Self {
        Self {
            client,
            caching: false,
            frequency_penalty: None,
            max_tokens: None,
            max_tool_iterations: None,
            middleware: Vec::new(),
            model: None,
            presence_penalty: None,
            reasoning_effort: None,
            seed: None,
            stop_sequences: Vec::new(),
            system: None,
            temperature: None,
            thinking_budget: None,
            tools: Vec::new(),
            top_k: None,
            top_p: None,
            state: None,
        }
    }

    pub fn caching(mut self) -> Self {
        self.caching = true;
        self.state = None;
        self
    }

    pub fn frequency_penalty(mut self, v: f64) -> Self {
        self.frequency_penalty = Some(v);
        self.state = None;
        self
    }

    pub fn max_tokens(mut self, n: u32) -> Self {
        self.max_tokens = Some(n);
        self.state = None;
        self
    }

    pub fn max_tool_iterations(mut self, n: u32) -> Self {
        self.max_tool_iterations = Some(n);
        self.state = None;
        self
    }

    pub fn middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self.state = None;
        self
    }

    pub fn model(mut self, name: impl Into<String>) -> Self {
        self.model = Some(name.into());
        self.state = None;
        self
    }

    pub fn presence_penalty(mut self, v: f64) -> Self {
        self.presence_penalty = Some(v);
        self.state = None;
        self
    }

    pub fn reasoning_effort(mut self, level: impl Into<String>) -> Self {
        self.reasoning_effort = Some(level.into());
        self.state = None;
        self
    }

    pub fn seed(mut self, n: i64) -> Self {
        self.seed = Some(n);
        self.state = None;
        self
    }

    pub fn stop_sequences(mut self, seqs: Vec<String>) -> Self {
        self.stop_sequences = seqs.into_iter().map(Into::into).collect();
        self.state = None;
        self
    }

    pub fn system(mut self, s: impl Into<String>) -> Self {
        self.system = Some(s.into());
        self.state = None;
        self
    }

    pub fn temperature(mut self, t: f64) -> Self {
        self.temperature = Some(t);
        self.state = None;
        self
    }

    pub fn thinking_budget(mut self, n: u32) -> Self {
        self.thinking_budget = Some(n);
        self.state = None;
        self
    }

    pub fn tool(mut self, t: Tool) -> Self {
        self.tools.push(t);
        self.state = None;
        self
    }

    pub fn top_k(mut self, n: u32) -> Self {
        self.top_k = Some(n);
        self.state = None;
        self
    }

    pub fn top_p(mut self, v: f64) -> Self {
        self.top_p = Some(v);
        self.state = None;
        self
    }

    pub async fn prompt(&mut self, msg: impl Into<String>) -> Result<Response, Error> {
        agent_prompt(self, msg).await
    }

    pub fn reset(&mut self) {
        agent_reset(self)
    }

}

// === Upload — FileUpload builder ===

#[derive(Clone)]
#[non_exhaustive]
pub struct Upload {
    pub(crate) client: Client,
    pub(crate) bytes: Vec<u8>,
    pub(crate) filename: Option<String>,
    pub(crate) middleware: Vec<MiddlewareFn>,
    pub(crate) mime_type: Option<String>,
    pub(crate) path: Option<String>,
}

impl Upload {
    fn new(client: Client) -> Self {
        Self {
            client,
            bytes: Vec::new(),
            filename: None,
            middleware: Vec::new(),
            mime_type: None,
            path: None,
        }
    }

    pub fn bytes(mut self, data: Vec<u8>) -> Self {
        self.bytes = data;
        self
    }

    pub fn filename(mut self, name: impl Into<String>) -> Self {
        self.filename = Some(name.into());
        self
    }

    pub fn middleware(mut self, fns: Vec<MiddlewareFn>) -> Self {
        self.middleware.extend(fns);
        self
    }

    pub fn mime_type(mut self, mime: impl Into<String>) -> Self {
        self.mime_type = Some(mime.into());
        self
    }

    pub fn path(mut self, p: impl Into<String>) -> Self {
        self.path = Some(p.into());
        self
    }

    pub async fn run(self) -> Result<File, Error> {
        upload_run(self).await
    }

}

