// Code generated by codegen/generate.py; DO NOT EDIT.


//! Catalogue data (ADR-019). Compiled-in model defs + per-model
//! capability lookup + per-provider live-endpoint config. Walked at
//! runtime by the Models / ScopedModels / Providers builders.

use crate::providers::generated::providers::ProviderName;
use crate::types::Capability;

/// CompiledModelDef is the static representation of one compiled-in
/// model. The hand-coded runtime in `models.rs` materialises an owned
/// `ModelInfo` from a `CompiledModelDef` on demand.
#[derive(Clone, Copy, Debug)]
pub struct CompiledModelDef {
    pub id: &'static str,
    pub provider: ProviderName,
    pub capabilities: &'static [Capability],
    pub display_name: &'static str,
    pub description: &'static str,
    pub context_window: i64,
    pub max_output: i64,
}

pub static COMPILED_IN_MODELS: &[CompiledModelDef] = &[
];

/// `(ProviderName, model_id) -> &[Capability]` lookup — consulted by
/// live-path parsers to enrich `ModelInfo` records with capability
/// data the wire never carries. Returns `None` when the SDK has no
/// ontology entry for the pair.
#[allow(dead_code)] // Phase 3: consumed by parser dispatch in catalogue_run_list
pub(crate) fn ontology_capabilities(
    provider: ProviderName,
    model_id: &str,
) -> Option<&'static [Capability]> {
    for m in COMPILED_IN_MODELS {
        if m.provider == provider && m.id == model_id {
            return Some(m.capabilities);
        }
    }
    None
}

/// Per-provider live-catalogue endpoint config (ADR-019). Providers
/// without a live endpoint return `None`; `ScopedModels::list` then
/// returns `Err(CatalogueError::NotSupported)`.
#[derive(Clone, Copy, Debug)]
pub struct CatalogueConfig {
    pub endpoint: &'static str,
    pub pagination: &'static str,
    pub spec_url: &'static str,
    pub spec_format: &'static str,
}

static ANTHROPIC_CATALOGUE: CatalogueConfig = CatalogueConfig {
    endpoint: "/v1/models",
    pagination: "CursorByLastID",
    spec_url: "https://github.com/anthropics/anthropic-sdk-typescript/blob/main/api.md",
    spec_format: "OpenAPI3",
};

static GOOGLE_CATALOGUE: CatalogueConfig = CatalogueConfig {
    endpoint: "/v1beta/models",
    pagination: "CursorOpaqueToken",
    spec_url: "https://generativelanguage.googleapis.com/$discovery/rest?version=v1beta",
    spec_format: "GoogleDiscovery",
};

static OPENAI_CATALOGUE: CatalogueConfig = CatalogueConfig {
    endpoint: "/v1/models",
    pagination: "PaginationNone",
    spec_url: "https://github.com/openai/openai-openapi/blob/master/openapi.yaml",
    spec_format: "OpenAPI3",
};

pub(crate) fn catalogue_config(provider: ProviderName) -> Option<&'static CatalogueConfig> {
    match provider {
        ProviderName::Anthropic => Some(&ANTHROPIC_CATALOGUE),
        ProviderName::Google => Some(&GOOGLE_CATALOGUE),
        ProviderName::OpenAI => Some(&OPENAI_CATALOGUE),
        _ => None,
    }
}
