// Code generated by codegen/generate.py; DO NOT EDIT.


//! Catalogue data (ADR-019). Compiled-in model defs + per-model
//! capability lookup + per-provider live-endpoint config. Walked at
//! runtime by the Models / ScopedModels / Providers builders.

use crate::providers::generated::providers::ProviderName;
use crate::types::Capability;

/// CompiledModelDef is the static representation of one compiled-in
/// model. The hand-coded runtime in `models.rs` materialises an owned
/// `ModelInfo` from a `CompiledModelDef` on demand.
#[derive(Clone, Copy, Debug)]
pub struct CompiledModelDef {
    pub id: &'static str,
    pub provider: ProviderName,
    pub capabilities: &'static [Capability],
    pub display_name: &'static str,
    pub description: &'static str,
    pub context_window: i64,
    pub max_output: i64,
}

pub static COMPILED_IN_MODELS: &[CompiledModelDef] = &[
    CompiledModelDef {
        id: "claude-haiku-4-5-20251001",
        provider: ProviderName::Anthropic,
        capabilities: &[Capability::ChatCompletion, Capability::ToolCalling],
        display_name: "Claude Haiku 4.5",
        description: "",
        context_window: 200000,
        max_output: 64000,
    },
    CompiledModelDef {
        id: "claude-opus-4-5-20251101",
        provider: ProviderName::Anthropic,
        capabilities: &[Capability::ChatCompletion, Capability::ToolCalling],
        display_name: "Claude Opus 4.5",
        description: "",
        context_window: 200000,
        max_output: 64000,
    },
    CompiledModelDef {
        id: "claude-opus-4-6",
        provider: ProviderName::Anthropic,
        capabilities: &[Capability::ChatCompletion, Capability::ToolCalling],
        display_name: "Claude Opus 4.6",
        description: "",
        context_window: 1000000,
        max_output: 128000,
    },
    CompiledModelDef {
        id: "claude-opus-4-7",
        provider: ProviderName::Anthropic,
        capabilities: &[Capability::ChatCompletion, Capability::ToolCalling],
        display_name: "Claude Opus 4.7",
        description: "",
        context_window: 1000000,
        max_output: 128000,
    },
    CompiledModelDef {
        id: "claude-sonnet-4-5-20250929",
        provider: ProviderName::Anthropic,
        capabilities: &[Capability::ChatCompletion, Capability::ToolCalling],
        display_name: "Claude Sonnet 4.5",
        description: "",
        context_window: 1000000,
        max_output: 64000,
    },
    CompiledModelDef {
        id: "claude-sonnet-4-6",
        provider: ProviderName::Anthropic,
        capabilities: &[Capability::ChatCompletion, Capability::ToolCalling],
        display_name: "Claude Sonnet 4.6",
        description: "",
        context_window: 1000000,
        max_output: 128000,
    },
    CompiledModelDef {
        id: "gemini-2.5-flash",
        provider: ProviderName::Google,
        capabilities: &[Capability::ChatCompletion, Capability::Reasoning, Capability::ToolCalling],
        display_name: "Gemini 2.5 Flash",
        description: "Stable version of Gemini 2.5 Flash",
        context_window: 1048576,
        max_output: 65536,
    },
    CompiledModelDef {
        id: "gemini-2.5-flash-lite",
        provider: ProviderName::Google,
        capabilities: &[Capability::ChatCompletion, Capability::ToolCalling],
        display_name: "Gemini 2.5 Flash-Lite",
        description: "Stable version of Gemini 2.5 Flash-Lite",
        context_window: 1048576,
        max_output: 65536,
    },
    CompiledModelDef {
        id: "gemini-2.5-pro",
        provider: ProviderName::Google,
        capabilities: &[Capability::ChatCompletion, Capability::Reasoning, Capability::ToolCalling],
        display_name: "Gemini 2.5 Pro",
        description: "Stable release of Gemini 2.5 Pro",
        context_window: 1048576,
        max_output: 65536,
    },
    CompiledModelDef {
        id: "gemini-3-pro-image-preview",
        provider: ProviderName::Google,
        capabilities: &[Capability::ImageGeneration],
        display_name: "Nano Banana Pro",
        description: "Gemini 3 Pro Image Preview",
        context_window: 131072,
        max_output: 32768,
    },
    CompiledModelDef {
        id: "gemini-3-pro-preview",
        provider: ProviderName::Google,
        capabilities: &[Capability::ChatCompletion, Capability::Reasoning, Capability::ToolCalling],
        display_name: "Gemini 3 Pro Preview",
        description: "Gemini 3 Pro Preview",
        context_window: 1048576,
        max_output: 65536,
    },
    CompiledModelDef {
        id: "gemini-3.1-flash-image-preview",
        provider: ProviderName::Google,
        capabilities: &[Capability::ImageGeneration],
        display_name: "Nano Banana 2",
        description: "Gemini 3.1 Flash Image Preview",
        context_window: 65536,
        max_output: 65536,
    },
    CompiledModelDef {
        id: "gpt-4o",
        provider: ProviderName::OpenAI,
        capabilities: &[Capability::ChatCompletion, Capability::ToolCalling],
        display_name: "",
        description: "",
        context_window: 0,
        max_output: 0,
    },
    CompiledModelDef {
        id: "gpt-4o-mini",
        provider: ProviderName::OpenAI,
        capabilities: &[Capability::ChatCompletion, Capability::ToolCalling],
        display_name: "",
        description: "",
        context_window: 0,
        max_output: 0,
    },
    CompiledModelDef {
        id: "gpt-5",
        provider: ProviderName::OpenAI,
        capabilities: &[Capability::ChatCompletion, Capability::Reasoning, Capability::ToolCalling],
        display_name: "",
        description: "",
        context_window: 0,
        max_output: 0,
    },
    CompiledModelDef {
        id: "gpt-image-1",
        provider: ProviderName::OpenAI,
        capabilities: &[Capability::ImageGeneration],
        display_name: "",
        description: "",
        context_window: 0,
        max_output: 0,
    },
    CompiledModelDef {
        id: "o1",
        provider: ProviderName::OpenAI,
        capabilities: &[Capability::ChatCompletion, Capability::Reasoning],
        display_name: "",
        description: "",
        context_window: 0,
        max_output: 0,
    },
    CompiledModelDef {
        id: "o3",
        provider: ProviderName::OpenAI,
        capabilities: &[Capability::ChatCompletion, Capability::Reasoning, Capability::ToolCalling],
        display_name: "",
        description: "",
        context_window: 0,
        max_output: 0,
    },
    CompiledModelDef {
        id: "o4-mini",
        provider: ProviderName::OpenAI,
        capabilities: &[Capability::ChatCompletion, Capability::Reasoning, Capability::ToolCalling],
        display_name: "",
        description: "",
        context_window: 0,
        max_output: 0,
    },
];

/// `(ProviderName, model_id) -> &[Capability]` lookup — consulted by
/// live-path parsers to enrich `ModelInfo` records with capability
/// data the wire never carries. Returns `None` when the SDK has no
/// ontology entry for the pair.
#[allow(dead_code)] // Phase 3: consumed by parser dispatch in catalogue_run_list
pub(crate) fn ontology_capabilities(
    provider: ProviderName,
    model_id: &str,
) -> Option<&'static [Capability]> {
    for m in COMPILED_IN_MODELS {
        if m.provider == provider && m.id == model_id {
            return Some(m.capabilities);
        }
    }
    None
}

/// Per-provider live-catalogue endpoint config (ADR-019). Providers
/// without a live endpoint return `None`; `ScopedModels::list` then
/// returns `Err(CatalogueError::NotSupported)`.
#[derive(Clone, Copy, Debug)]
pub struct CatalogueConfig {
    pub endpoint: &'static str,
    pub pagination: &'static str,
    pub spec_url: &'static str,
    pub spec_format: &'static str,
}

static ANTHROPIC_CATALOGUE: CatalogueConfig = CatalogueConfig {
    endpoint: "/v1/models",
    pagination: "CursorByLastID",
    spec_url: "https://github.com/anthropics/anthropic-sdk-typescript/blob/main/api.md",
    spec_format: "OpenAPI3",
};

static GOOGLE_CATALOGUE: CatalogueConfig = CatalogueConfig {
    endpoint: "/v1beta/models",
    pagination: "CursorOpaqueToken",
    spec_url: "https://generativelanguage.googleapis.com/$discovery/rest?version=v1beta",
    spec_format: "GoogleDiscovery",
};

static OPENAI_CATALOGUE: CatalogueConfig = CatalogueConfig {
    endpoint: "/v1/models",
    pagination: "PaginationNone",
    spec_url: "https://github.com/openai/openai-openapi/blob/master/openapi.yaml",
    spec_format: "OpenAPI3",
};

pub(crate) fn catalogue_config(provider: ProviderName) -> Option<&'static CatalogueConfig> {
    match provider {
        ProviderName::Anthropic => Some(&ANTHROPIC_CATALOGUE),
        ProviderName::Google => Some(&GOOGLE_CATALOGUE),
        ProviderName::OpenAI => Some(&OPENAI_CATALOGUE),
        _ => None,
    }
}
