// Code generated by codegen/generate.py; DO NOT EDIT.

use crate::types::{Capability, Provider, Usage};
use std::collections::HashMap;

/// AudioData is one decoded audio payload returned in a MusicResponse. Same shape as MediaRef (mime type + raw bytes) but a distinct type so capability-specific return semantics stay typed: MusicResponse.audio carries decoded outputs; MediaRef appears in input payloads.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct AudioData {
    /// mime_type is the IANA media type of the returned audio (audio/wav, audio/mpeg). Drives the file extension the caller picks for storage.
    pub mime_type: String,

    /// bytes is the raw (not encoded) decoded audio payload. The SDK decodes the provider wire format (base64 for Vertex/Gemini, hex for MiniMax) before returning so callers always see raw bytes.
    pub bytes: Vec<u8>,
}

/// BatchHandle is a value struct identifying a submitted batch. Cross-process resume works by persisting the three fields and reconstructing the handle.
#[derive(Clone, Debug, PartialEq)]
pub struct BatchHandle {
    /// id is the provider-assigned batch identifier returned by the create endpoint. Opaque to the SDK; round-tripped to the polling and result endpoints verbatim.
    pub id: String,

    /// provider is the Provider config used to submit the batch. Carried on the handle so Wait knows where to poll without re-parameterising the client.
    pub provider: Provider,

    /// raw is the ADR-014 opt-in: when true, every Response returned from Wait carries Response.raw set to the parsed per-item provider body. Text.Batch propagates the chain's .raw() flag onto the handle; cross-process resume callers set the field directly.
    pub raw: bool,
}

/// File is a reference to an uploaded file. Returned by UploadFile and attached to subsequent text-generation requests via Request.Files.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct File {
    /// id is the provider-assigned file identifier returned by the upload endpoint. Empty when the provider returns only a URI.
    pub id: String,

    /// uri is the provider-hosted URI of the uploaded file. Used in subsequent prompts to refer back to the file without re-uploading.
    pub uri: String,

    /// mime_type is the IANA media type of the uploaded file as recorded by the provider (e.g., application/pdf, image/png). Carried so downstream prompts can route the file to the correct vision / document / audio path.
    pub mime_type: String,

    /// name is the original filename supplied at upload time. Round-tripped through the provider so the caller can correlate the handle with the source artifact.
    pub name: String,
}

/// ImageData is one decoded image payload returned in an ImageResponse. Same shape as MediaRef (mime type + raw bytes) but a distinct type so capability-specific return semantics stay typed: ImageResponse.images carries decoded outputs; MediaRef appears in input payloads and edit masks.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ImageData {
    /// mime_type is the IANA media type of the returned image (image/png, image/jpeg, image/webp). Drives the file extension or data URI scheme the caller picks for storage.
    pub mime_type: String,

    /// bytes is the raw (not base64-encoded) decoded image payload. The SDK decodes provider wire format (base64, URL fetch) before returning so callers always see raw bytes.
    pub bytes: Vec<u8>,
}

/// ImageResponse is the universal image-generation response container returned by Image.Generate. Carries the decoded images, optional text captions/refusals, usage, and the same finish-reason / finish-message / raw fields the text-gen Response carries.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ImageResponse {
    /// images are the decoded image payloads (mime type + raw bytes) returned by the provider. Empty when the provider blocks or refuses the request — inspect FinishReason / FinishMessage for the cause.
    pub images: Vec<ImageData>,

    /// text is the optional text response accompanying the images (captions, refusals, or model commentary). Populated only when the caller opted into mixed text + image output via the builder's IncludeText() chain method on providers that support it.
    pub text: String,

    /// usage holds token consumption metrics for the image-generation call. Google reports image-output tokens in usageMetadata.candidatesTokenCount; OpenAI Images API and Vertex Imagen do not return token counts so this stays zero on those providers.
    pub usage: Usage,

    /// finish_reason is the provider stop signal. Examples per provider: Google STOP/IMAGE_OTHER/SAFETY/MAX_TOKENS; OpenAI Images API has no equivalent field (always empty); xAI Grok has no equivalent field (always empty); Vertex Imagen surfaces the RAI filter reason when content is blocked.
    pub finish_reason: String,

    /// finish_message is the free-text provider explanation of the stop signal. Gemini populates this for non-success FinishReason values; other providers leave it empty. Use as the user-facing message when len(Images) == 0.
    pub finish_message: String,

    /// raw is the parsed provider response body, populated only when the caller opted in via the builder's .raw() chain method (ADR-014). Type-erased — consumers cast to a provider-shape type for fields the universal ImageResponse does not carry.
    pub raw: Option<serde_json::Value>,
}

/// LiveResult is returned by c.Models.Live(ctx) — the aggregated cross-provider live result. Partial success is the documented normal case: per-provider failures land in Errors while everything that succeeded lands in Models.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct LiveResult {
    /// models are the ModelInfo records that returned successfully across configured providers. Sorted by (provider name, id) for deterministic ordering across calls.
    pub models: Vec<ModelInfo>,

    /// errors is the per-provider failure map. Empty when every configured provider succeeded. Keyed by Provider; each value carries the per-provider error sentinel (ErrModelsScope / ErrModelsUnavailable / ErrModelsNotSupported).
    pub errors: HashMap<String, ProviderError>,
}

/// MediaRef is an inline media payload (mime type + raw bytes). Reused by every Part variant that carries non-text content, and by image-generation knobs like Mask that pass through a single binary blob.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct MediaRef {
    /// mime_type is the IANA media type of the bytes payload (image/png, image/jpeg, audio/wav, ...). Drives both the wire encoding (base64 mime prefix on data URIs) and provider routing on multimodal endpoints.
    pub mime_type: String,

    /// bytes is the raw (not base64-encoded) media payload. The transform layer base64-encodes at wire time per provider; callers always pass raw bytes.
    pub bytes: Vec<u8>,
}

/// Message is a single turn in a multi-turn conversation. Discriminated by role: text turns set content; assistant-with-tools turns set tool_calls; tool turns set tool_result. Consumers MUST inspect role before reading the optional tool-turn fields. ADR-020 extends Message with tool_calls and tool_result so *Agent history round-trips fully across process boundaries.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Message {
    /// role is the speaker identifier. Conventionally "user", "assistant", or "tool"; provider transforms may map to other roles (Bedrock's "USER"/"ASSISTANT", Google's "user"/"model").
    pub role: String,

    /// content is the turn's text content. Empty on assistant-with-tools turns and on tool turns (the carrier field switches to tool_calls or tool_result respectively).
    pub content: String,

    /// tool_calls are the tool invocations the model produced on an assistant turn. Defaults to an empty list (never null) so consumers can iterate without a None-guard regardless of role. Empty on text turns and tool turns.
    pub tool_calls: Vec<ToolCall>,

    /// tool_result is the tool execution result on a role=tool turn. Null on text turns and assistant turns. Singular (not plural) because one tool turn carries exactly one result.
    pub tool_result: Option<ToolResult>,
}

/// ModelInfo is the universal model descriptor returned by c.Models methods (compiled-in and live). Capabilities is always ontology-derived — never from wire data; wire fills the metadata fields when present.
#[derive(Clone, Debug, PartialEq)]
pub struct ModelInfo {
    /// id is the provider-scoped model identifier (e.g. claude-opus-4-7, gpt-5, gemini-2.5-flash). Round-tripped to provider endpoints verbatim.
    pub id: String,

    /// provider is the Provider value that exposes this model. Used by Models.Provider(m.Provider).Get(ctx, m.ID) to round-trip back to live data when needed.
    pub provider: Provider,

    /// capabilities is the SDK's understanding of what this model supports — chat completion, image generation, tool calling, etc. Always populated from the ontology, never from wire data. Empty (nil) for live IDs the SDK does not recognise.
    pub capabilities: Vec<Capability>,

    /// display_name is the human-readable name when the provider supplies one (Anthropic display_name, Google displayName). Empty when the provider's wire shape does not carry one or for compiled-in entries.
    pub display_name: String,

    /// description is the provider's free-text description (Google description). Empty for providers that do not publish a description field and for compiled-in entries.
    pub description: String,

    /// context_window is the maximum input token count when published (Anthropic max_input_tokens, Google inputTokenLimit). Zero when the provider does not publish it (OpenAI-shape cohort) or for compiled-in entries without a curated value.
    pub context_window: i64,

    /// max_output is the maximum output token count when published (Anthropic max_tokens, Google outputTokenLimit). Zero when the provider does not publish it or for compiled-in entries.
    pub max_output: i64,

    /// created is the Unix-timestamp creation time when the provider publishes one (Anthropic created_at parsed to Unix, OpenAI created). Zero for compiled-in entries and providers that do not publish it.
    pub created: i64,

    /// raw is the parsed provider-native record for this model, populated only when the caller opted in via the builder's .Raw() chain method (ADR-014). Type-erased — consumers cast to a provider-shape type for fields the universal ModelInfo does not carry (Anthropic capability matrix, Google supportedGenerationMethods, etc.).
    pub raw: Option<serde_json::Value>,
}

/// MusicResponse is the universal music-generation response container returned by Music.Generate. Carries the decoded audio, optional text (generated lyrics / commentary), usage, and the same finish-reason / finish-message / raw fields the image-gen and text-gen responses carry.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct MusicResponse {
    /// audio are the decoded audio payloads (mime type + raw bytes) returned by the provider. Empty when the provider blocks or refuses the request — inspect FinishReason / FinishMessage for the cause.
    pub audio: Vec<AudioData>,

    /// text is the optional text accompanying the audio (generated lyrics, song structure, or model commentary). Populated by Gemini Lyria 3; empty on Vertex Lyria 2 and MiniMax.
    pub text: String,

    /// usage holds token consumption metrics for the music-generation call. None of the three verified providers report audio-output tokens as a distinct dimension; this stays zero unless a provider surfaces counts (ADR-033 OQ-3).
    pub usage: Usage,

    /// finish_reason is the provider stop signal. Gemini surfaces STOP/SAFETY etc.; Vertex Imagen-style providers surface a RAI filter reason when content is blocked; MiniMax carries a base_resp status. Optional.
    pub finish_reason: String,

    /// finish_message is the free-text provider explanation of the stop signal. Use as the user-facing message when len(Audio) == 0.
    pub finish_message: String,

    /// raw is the parsed provider response body, populated only when the caller opted in via the builder's .raw() chain method (ADR-014). Type-erased — consumers cast to a provider-shape type for fields the universal MusicResponse does not carry.
    pub raw: Option<serde_json::Value>,
}

/// ProviderError is the per-provider failure carried in LiveResult.errors (ADR-019 Amendment 1). Discriminated by Kind so consumers can branch typed in any SDK; Message is the human-readable form for display.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ProviderError {
    /// kind is the sentinel discriminant: "not_supported", "unavailable", or "scope". Mirrors the three Err* sentinels declared in ADR-019 § Error story. String (not enum) keeps the codegen-table footprint at zero and dodges the Python str(Enum) trap that Phase 2.5's review surfaced.
    pub kind: String,

    /// message is the human-readable explanation. Free-form; not part of the contract beyond display.
    pub message: String,
}

/// Response is the universal response container returned by text-generation terminals (Text.Prompt, Agent.Prompt). Five fields; all five are core (no per-capability augmentation).
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Response {
    /// text is the assistant's response text, extracted from the provider response body at the path declared by llm:hasResponseTextPath.
    pub text: String,

    /// usage holds token consumption metrics — input, output, cache_write, cache_read, and reasoning counts. Each dimension is populated from the provider-specific path declared in the ontology.
    pub usage: Usage,

    /// finish_reason is the provider stop signal, passed through verbatim. Empty when the provider response carries no signal or the parser does not yet read this provider's location. Examples per provider: Google STOP/MAX_TOKENS/SAFETY/RECITATION; OpenAI stop/length/content_filter/tool_calls; Anthropic end_turn/max_tokens/stop_sequence/tool_use; xAI stop/length/content_filter.
    pub finish_reason: String,

    /// finish_message is the provider-supplied free-text explanation of the stop signal. Populated by Google when present; OpenAI / Anthropic / xAI do not carry an equivalent field, so this stays empty for them.
    pub finish_message: String,

    /// raw is the parsed provider response body, populated only when the caller opted in via the typed builder's .raw() chain method (ADR-014). Type-erased — provider-specific fields (Anthropic citations, OpenAI logprobs, Google promptFeedback, ...) are not part of the universal Response shape; consumers cast to a provider-shape type once they know which provider they're talking to.
    pub raw: Option<serde_json::Value>,
}

/// SpeechResponse is the universal text-to-speech response container returned by Speech.Generate. Carries the synthesized audio (a single clip), the provider-reported usage, and an optional finish reason — reusing the music pipeline's AudioData container unchanged (ADR-049).
#[derive(Clone, Debug, Default, PartialEq)]
pub struct SpeechResponse {
    /// audio is the synthesized audio (mime type + raw bytes). One synthesis yields one clip, so this is a single AudioData, not a list (ADR-049 OQ-4).
    pub audio: AudioData,

    /// usage holds provider-reported usage. Inworld returns usage.processedCharactersCount, but the SDK does not yet surface it: the Usage carrier has no characters axis and OQ-3 declined to overload a token axis, so this stays zero pending a typed characters dimension (ADR-049 OQ-3, deferred).
    pub usage: Usage,

    /// finish_reason is the provider stop signal, when present. Optional.
    pub finish_reason: String,
}

/// ToolCall is a single tool invocation issued by the model on an assistant turn. Carries the provider-issued id, the tool name, and the JSON-decoded argument object. ADR-020 promotes this from a private per-SDK type into a public generated struct so *Agent history can carry tool turns end to end.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ToolCall {
    /// id is the provider-issued call identifier. Round-tripped to ToolResult.tool_use_id on the response turn so the model can correlate the request with its execution outcome.
    pub id: String,

    /// name is the tool name the model selected. Matches the name registered via the Tool functional option on the *Agent builder.
    pub name: String,

    /// input is the JSON-decoded argument object the model passed. Null on absent or empty arg sets; otherwise a provider-specific JSON value (typically an object, but type-erased through OptionalAny because schemas vary per tool).
    pub input: Option<serde_json::Value>,
}

/// ToolResult is the execution result of one tool call, attached to a role=tool turn. Pairs with a prior ToolCall via tool_use_id. ADR-020 promotes this from a private per-SDK type into a public generated struct.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ToolResult {
    /// tool_use_id is the ToolCall.id this result responds to. Lets the model correlate the response with its earlier request when multiple tools are called in parallel.
    pub tool_use_id: String,

    /// content is the stringified tool return value. Tool authors that return non-string types must stringify before yielding; this stays string-typed to keep the wire shape uniform across providers.
    pub content: String,
}

/// TranscriptSegment is one timed span of transcript (ADR-048). Slice-1 segments carry text + millisecond offsets + an optional diarized speaker label; confidence (a float) is deferred until the struct-field type table gains a float type (ADR-048 OQ-4).
#[derive(Clone, Debug, Default, PartialEq)]
pub struct TranscriptSegment {
    /// text is the segment text.
    pub text: String,

    /// start is the segment start offset in milliseconds.
    pub start: i64,

    /// end is the segment end offset in milliseconds.
    pub end: i64,

    /// speaker is the diarized speaker label, when the provider reports one. Empty otherwise.
    pub speaker: String,
}

/// TranscriptionHandle is a value struct identifying a submitted transcription job, modeled on VideoHandle / BatchHandle (ADR-014 / ADR-034). Cross-process resume works by persisting the fields and reconstructing the handle; the poll loop (Wait) is hand-written runtime, not part of the generated value.
#[derive(Clone, Debug, PartialEq)]
pub struct TranscriptionHandle {
    /// id is the provider-assigned transcript id returned by the submit endpoint (AssemblyAI: id). Opaque to the SDK; round-tripped to the poll endpoint verbatim.
    pub id: String,

    /// provider is the Provider config used to submit the job. Carried on the handle so Wait knows where to poll without re-parameterising the client.
    pub provider: Provider,
}

/// TranscriptionResponse is the universal speech-to-text response container returned by TranscriptionHandle.Wait. Carries the full transcript text, the timed transcript segments, and the provider-reported usage. The container is text-shaped, NOT a media *Data container — the structural divergence from video (ADR-048).
#[derive(Clone, Debug, Default, PartialEq)]
pub struct TranscriptionResponse {
    /// text is the full transcript text.
    pub text: String,

    /// segments are the timed transcript segments (start/end offsets in milliseconds). Empty when the provider returns no word-level timing.
    pub segments: Vec<TranscriptSegment>,

    /// usage holds provider-reported usage. AssemblyAI bills by audio duration, not tokens; this stays zero unless a provider surfaces a token axis (ADR-048 OQ-2).
    pub usage: Usage,
}

/// VideoData is one finished video returned in a VideoResponse. Models bytes (downloaded payload) XOR url (a provider link or caller S3 URI) — the source-XOR pattern (VID-004). url-delivery and output-uri providers set url; download-delivery providers set bytes.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct VideoData {
    /// mime_type is the IANA media type of the video (video/mp4). Drives the file extension the caller picks for storage.
    pub mime_type: String,

    /// url is the provider link (grok: a temporary xAI-hosted URL) or the caller-supplied S3 URI (Bedrock). Set for url and output-uri delivery; empty for download delivery. XOR with bytes.
    pub url: String,

    /// bytes is the raw (not encoded) video payload, present only for download-delivery providers the SDK fetched on the caller's behalf. Empty for url and output-uri delivery. XOR with url.
    pub bytes: Vec<u8>,

    /// duration_seconds is the duration of the finished video in seconds, when the provider reports it (grok: video.duration). Zero when unreported.
    pub duration_seconds: i64,
}

/// VideoHandle is a value struct identifying a submitted video job, modeled on BatchHandle (ADR-014). Cross-process resume works by persisting the fields and reconstructing the handle; the poll loop (Wait) is hand-written runtime, not part of the generated value.
#[derive(Clone, Debug, PartialEq)]
pub struct VideoHandle {
    /// id is the provider-assigned request id returned by the submit endpoint (grok: request_id). Opaque to the SDK; round-tripped to the poll endpoint verbatim.
    pub id: String,

    /// provider is the Provider config used to submit the job. Carried on the handle so Wait knows where to poll without re-parameterising the client.
    pub provider: Provider,

    /// raw is the ADR-014 opt-in: when true, the VideoResponse returned from Wait carries raw set to the parsed provider poll body. Submit propagates the chain's .raw() flag onto the handle; cross-process resume callers set it directly.
    pub raw: bool,

    /// model is the submitted model id, carried so Wait can build a model-templated poll URL (Vertex Veo polls POST /{model}:fetchPredictOperation). Submit sets it from the request; empty for providers whose poll endpoint does not template the model.
    pub model: String,
}

/// VideoResponse is the universal video-generation response container returned by VideoHandle.Wait. Carries the finished video references, usage, and the same finish-reason / finish-message / raw fields the image-gen and music-gen responses carry.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct VideoResponse {
    /// videos are the finished video references. url-delivery providers (grok) fill VideoData.url; download-delivery providers fill VideoData.bytes with bytes the SDK fetched; output-uri providers (Bedrock) carry the caller S3 URI in url. Empty when the job failed — inspect FinishReason / FinishMessage.
    pub videos: Vec<VideoData>,

    /// usage holds token consumption metrics for the video-generation call. No verified provider reports a video usage axis yet; this stays zero unless a provider surfaces counts (ADR-034 OQ-3).
    pub usage: Usage,

    /// finish_reason is the provider terminal status / stop signal (grok: a non-done status such as expired or failed). Empty on success. Optional.
    pub finish_reason: String,

    /// finish_message is the free-text provider explanation of a non-success status (grok: error.message on a failed job). Use as the user-facing message when len(Videos) == 0.
    pub finish_message: String,

    /// raw is the parsed provider poll response body, populated only when the caller opted in via the builder's .raw() chain method (ADR-014). Type-erased — consumers cast to a provider-shape type for fields the universal VideoResponse does not carry.
    pub raw: Option<serde_json::Value>,
}
