// Code generated by codegen/generate.py; DO NOT EDIT.

//! Current generation of the on-disk wire format for serialized
//! agent history (ADR-023 STAB-001).

pub const WIRE_SCHEMA_VERSION: u32 = 1;
